name: Build binaries

on:
  workflow_dispatch
  #schedule:
  #  - cron: '5 5 * * *'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  REDLIB_REPO: https://github.com/Silvenga/redlib.git
  REDLIB_ROOT_DIR: /tmp/redlib
  REDLIB_BIN_NAME: redlib-silvenga
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0

defaults:
  run:
    shell: bash

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      REDLIB_PREBUILT_LATEST_TAG: ${{ steps.release_latest_tag.outputs.REDLIB_PREBUILT_LATEST_TAG }}
      REDLIB_CURRENT_COMMIT_ID: ${{ steps.release_commit_id.outputs.REDLIB_CURRENT_COMMIT_ID }}
      REDLIB_VERSION: ${{ steps.release_version.outputs.REDLIB_VERSION }}

    steps:
      - name: Get latest release tag of this repo
        id: release_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/
          REDLIB_PREBUILT_LATEST_TAG=$(gh release list -R mycodedoesnotcompile2/redib_silvenga_fork --json tagName -L 1 --jq '.[].tagName' --exclude-drafts --exclude-pre-releases)
          echo "REDLIB_PREBUILT_LATEST_TAG=$REDLIB_PREBUILT_LATEST_TAG" >> $GITHUB_OUTPUT
          echo "REDLIB_PREBUILT_LATEST_TAG=$REDLIB_PREBUILT_LATEST_TAG" >> $GITHUB_ENV

      - name: Clone redlib repo and check if there is a new and uncompiled yet version
        id: release_commit_id
        run: |
          cd /tmp/
          git clone "$REDLIB_REPO" --branch "switch-to-wreq" --single-branch redlib

          cd "$REDLIB_ROOT_DIR"
          REDLIB_CURRENT_COMMIT_ID=$(git rev-parse --short HEAD)
          echo "REDLIB_CURRENT_COMMIT_ID=$REDLIB_CURRENT_COMMIT_ID" >> $GITHUB_OUTPUT

          # case: no new commit => abort the workflow
          if [[ $REDLIB_PREBUILT_LATEST_TAG == $REDLIB_CURRENT_COMMIT_ID ]]; then
            echo "[!] No new version to compile"
            exit 100
          fi

      - name: Get redlib version
        id: release_version_cargo_get
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.version
          options: --entry "$REDLIB_ROOT_DIR/Cargo.toml"

      - name: Set REDLIB_VERSION build variable
        id: release_version
        run: |
          REDLIB_VERSION=${{ steps.release_version_cargo_get.outputs.metadata }}
          echo "REDLIB_VERSION=$REDLIB_VERSION" >> $GITHUB_OUTPUT


##############

  build:
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-latest
          
          - TARGET: x86_64-unknown-linux-musl
            OS: ubuntu-latest
            CROSS_CHAIN: https://musl.cc/x86_64-linux-musl-cross.tgz
          
          - TARGET: aarch64-unknown-linux-gnu
            OS: ubuntu-24.04-arm
          
          - TARGET: aarch64-unknown-linux-musl
            OS: ubuntu-24.04-arm

          - TARGET: armv7-unknown-linux-gnueabihf
            OS: ubuntu-latest
          
          - TARGET: armv7-unknown-linux-musleabihf
            OS: ubuntu-latest
          
          - TARGET: arm-unknown-linux-gnueabihf
            OS: ubuntu-latest

          - TARGET: arm-unknown-linux-musleabihf
            OS: ubuntu-latest
          
          - TARGET: aarch64-apple-darwin
            OS: macos-latest

          - TARGET: x86_64-apple-darwin
            OS: macos-26-intel
          
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest

          - TARGET: aarch64-pc-windows-msvc
            OS: windows-11-arm
            
    runs-on: ${{ matrix.OS }}

    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      CONTAINER: ${{ matrix.CONTAINER }}
      CROSS_CHAIN: ${{ matrix.CROSS_CHAIN }}
      
      REDLIB_PREBUILT_LATEST_TAG: ${{ needs.checkout.outputs.REDLIB_PREBUILT_LATEST_TAG }}
      REDLIB_VERSION: ${{ needs.checkout.outputs.REDLIB_VERSION }}

    steps:
      - name: Clone redlib repo
        run: |
          cd /tmp/
          git clone "$REDLIB_REPO" --branch "switch-to-wreq" --single-branch redlib
      
      - name: Install and configure dependencies
        run: |
          if [[ $OS =~ ^ubuntu.*$ ]]; then
            $APT update
            $APT install crossbuild-essential-armhf
          fi

          # for musl builds
          if [[ $TARGET == *"-musl"* ]]; then
            $APT install musl-tools
          fi

          # for arm targets
          if [[ $TARGET == "arm"* ]]; then
            cd "$REDLIB_ROOT_DIR"
            cargo install --force --locked bindgen-cli
          fi

          
          if [[ -v $CROSS_CHAIN ]]; then 
            echo "$CROSS_CHAIN"
            mkdir -p /tmp/crosschain
            cd /tmp/crosschain/
            wget -nv "$CROSS_CHAIN" -o musl.tar.gz
            tar -xzf musl.tar.gz
            echo "$PWD/x86_64-linux-musl-cross/bin" >> $GITHUB_PATH
          fi

          # some additional configuration for cross-compilation on linux
          # cat >>~/.cargo/config.toml <<EOF
          # [target.armv7-unknown-linux-gnueabihf]
          # linker = "arm-linux-gnueabihf-gcc"
          # [target.armv7-unknown-linux-musleabihf]
          # linker = "arm-linux-gnueabihf-gcc"
          # [target.arm-unknown-linux-gnueabihf]
          # linker = "arm-linux-gnueabihf-gcc"
          # [target.arm-unknown-linux-musleabihf]
          # linker = "arm-linux-gnueabihf-gcc"
          # EOF
      
      - name: Install rust target
        run: rustup target add $TARGET
        
      - name: Run build
        run: |
          cd $REDLIB_ROOT_DIR
          cargo build --release --target $TARGET
      
      - name: List build information
        run: |
          OLD_REDLIB_BIN_PATH="$REDLIB_ROOT_DIR/target/$TARGET/release/redlib"

          REDLIB_BIN_PATH="${{ runner.temp }}/$REDLIB_BIN_NAME-$REDLIB_VERSION-$TARGET"
          if [[ $OS =~ ^windows.*$ ]]; then
            REDLIB_BIN_PATH="${{ runner.temp }}/$REDLIB_BIN_NAME-$REDLIB_VERSION-$TARGET.exe"
          fi
          REDLIB_BIN_HASH_PATH="$REDLIB_BIN_PATH.sha256.txt"
          
          cp -f "$OLD_REDLIB_BIN_PATH" "$REDLIB_BIN_PATH"
          ls -alh "$REDLIB_BIN_PATH"
          ldd "$REDLIB_BIN_PATH" || true
          "$REDLIB_BIN_PATH" -V || true

          cd "$(dirname "$REDLIB_BIN_PATH")"
          sha256sum --tag "$(basename "$REDLIB_BIN_PATH")" | tee "$REDLIB_BIN_HASH_PATH"
          
          echo "REDLIB_BIN_PATH=$REDLIB_BIN_PATH" >> $GITHUB_ENV
          echo "REDLIB_BIN_HASH_PATH=$REDLIB_BIN_HASH_PATH" >> $GITHUB_ENV


      - name: List redlib options 
        run: |
          "$REDLIB_BIN_PATH" -h || true

      
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.TARGET }}
          path: |
            ${{ env.REDLIB_BIN_PATH }}
            ${{ env.REDLIB_BIN_HASH_PATH }}

##############

  deploy_release:
    needs: [checkout, build]
    runs-on: ubuntu-latest
    env:
       REDLIB_CURRENT_COMMIT_ID: ${{ needs.checkout.outputs.REDLIB_CURRENT_COMMIT_ID }}
       REDLIB_VERSION: ${{ needs.checkout.outputs.REDLIB_VERSION }}
    
    steps:
     - name: Download Artifact
       uses: actions/download-artifact@v8
       with:
        pattern: binary-*
        merge-multiple: true
        path: /tmp/results

     - name: List target
       run: |
          cd "/tmp/results"
          ls -alh
  
          RELEASE_NOTES="/tmp/release_notes.txt"
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
          
          cat *.sha256.txt > "$RELEASE_NOTES"
          mkdir -p "/tmp/hashes"
          mv -f *.sha256.txt "/tmp/hashes/"
  
     - name: Create a new Github release
       uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe #v2.6.1
       with:
         make_latest: true
         body_path: ${{ env.RELEASE_NOTES }}
         name: version ${{ env.REDLIB_VERSION }} - build ${{ env.REDLIB_CURRENT_COMMIT_ID }}
         tag_name: ${{ env.REDLIB_CURRENT_COMMIT_ID }}
         files: |
           /tmp/results/${{ env.REDLIB_BIN_NAME }}-*
